[package]
name = "hecs-arkanoid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.30.9"
hecs = "0.11.0"
lazy_static = "1.5.0"
rand = "0.10.0"
raylib = "5.5.1"
strum = "0.28.0"
strum_macros = "0.28.0"
